### PR TITLE
fix #15

### LINKED ISSUE #15: Add functionality to make password visible
**Is your feature request related to a problem? Please describe.**
Currently there is no option to view the entire password that the user enters.

**Describe the solution you'd like**
Add a "visibility" icon and allow the user to toggle visibility of the password.

### PR DESCRIPTION
**Pull request by BhushanNalawade**
I have added the password visible and hide toggle button.

### CODE REVIEW

**Comment by prathameshgaikwad** [comment]
A few things,

- It is generally a good practice to first get an issue assigned to yourself, before you submit a pull request. This repo is not very busy, but in cases where it is, you first get the issue assigned to yourself and then work on it. Otherwise, your effort may go in vain, and someone else's pull request will get merged.
- I see you have made the changes in the "CustomInput" component. Good job with that, however, it has uses in other places.
- Firstly define the type of the "type" prop that you have included. You can make it optional too.
- Depending on whether you've made the "type" prop optional or not, you must make changes in places where the concerned component is used.

**Comment by BhushanNalawade** [comment]
make the type as optional

**Review by BhushanNalawade — COMMENTED** [review]
git
here is the change.

**Comment by prathameshgaikwad** [comment]
Well done @BhushanNalawade! Thanks for working on this.

**Pull request merged**
